#DBconfig
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://drdshhid9174116j.drds.aliyuncs.com:3306/singleuser?
    username: singleuser
    password: Drgou_druser123

useUnicode: true&autoReconnect=true&allowMultiQueries=true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
